int strcmp(char *str1, char*str2);
int strlen(char* string);
int mod(int x, int y);
int div(int x, int y);
//void strncpy(char *destination, char *source, int n);
void strncopy(char* src, char* dest, char x);
void splitstring(char *src, char* part1, char* part2, char x);
void strcpybounded(char *dest, char *src, int n);
void strcopy(char *src, char *dest);
void copySegmentSectorSectors(char *dest, char *src, int n);